services:
  server:
    build:
      context: .
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - BASE_URL=https://host.docker.internal:7777/api
      - HOST=0.0.0.0
      - PORT=9777
      - NODE_ENV=production
    ports:
      - 9777:9777
    restart: unless-stopped
